// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "TechnicalInterviewPractice",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "Problem03PermissionManager", targets: ["Problem03PermissionManager"]),
        .library(name: "Problem18InventoryReservationLedger", targets: ["Problem18InventoryReservationLedger"]),
        .library(name: "Problem10DispatchManager", targets: ["Problem10DispatchManager"]),
        .library(name: "Problem05MedicationTitration", targets: ["Problem05MedicationTitration"]),
        .library(name: "Problem13ContractLifecycle", targets: ["Problem13ContractLifecycle"]),
        .library(name: "Problem15TicTacToeEngine", targets: ["Problem15TicTacToeEngine"]),
        .library(name: "Problem02APIRateLimiter", targets: ["Problem02APIRateLimiter"]),
        .library(name: "Problem11CoverageTracker", targets: ["Problem11CoverageTracker"]),
        .library(name: "Problem19OfflineTelemetryBatchProcessor", targets: ["Problem19OfflineTelemetryBatchProcessor"]),
        .library(name: "Problem21VersionedPayloadMigration", targets: ["Problem21VersionedPayloadMigration"]),
        .library(name: "Problem22UndoRedoCommandStack", targets: ["Problem22UndoRedoCommandStack"]),
        .library(name: "Problem20OfflineSyncConflictResolver", targets: ["Problem20OfflineSyncConflictResolver"]),
        .library(name: "Problem23AvailabilityZoneMaintenancePlanner", targets: ["Problem23AvailabilityZoneMaintenancePlanner"]),
        .library(name: "Problem24SensorDriftWindowDetector", targets: ["Problem24SensorDriftWindowDetector"]),
        .library(name: "Problem25WarehouseGridRoutePlanner", targets: ["Problem25WarehouseGridRoutePlanner"]),
        .library(name: "Problem26FirmwareBundleBudgetPlanner", targets: ["Problem26FirmwareBundleBudgetPlanner"]),
        .library(name: "Problem27LogTokenSegmenter", targets: ["Problem27LogTokenSegmenter"]),
        .library(name: "Problem28BuildRegressionChainAnalyzer", targets: ["Problem28BuildRegressionChainAnalyzer"]),
        .library(name: "Problem29RuleGroupingAnalyzer", targets: ["Problem29RuleGroupingAnalyzer"]),
        .library(name: "Problem30DocumentRevisionDiffEngine", targets: ["Problem30DocumentRevisionDiffEngine"]),
        .library(name: "Problem31PipelineBufferRemovalPlanner", targets: ["Problem31PipelineBufferRemovalPlanner"]),
        .library(name: "Problem32StorageArbitrageScheduler", targets: ["Problem32StorageArbitrageScheduler"]),
        .library(name: "Problem33FirmwareTelemetryBufferCompactor", targets: ["Problem33FirmwareTelemetryBufferCompactor"]),
        .library(name: "Problem34FloodplainPondingAnalyzer", targets: ["Problem34FloodplainPondingAnalyzer"]),
        .library(name: "Problem35RedirectChainResolver", targets: ["Problem35RedirectChainResolver"]),
        .library(name: "Problem36DispatchWindowMatcher", targets: ["Problem36DispatchWindowMatcher"]),
        .library(name: "Problem37LedgerNettingFinder", targets: ["Problem37LedgerNettingFinder"]),
        .library(name: "Problem68ClinicRoomBookingSelector", targets: ["Problem68ClinicRoomBookingSelector"]),
        .library(name: "Problem70DepotChargerCapacitySizer", targets: ["Problem70DepotChargerCapacitySizer"]),
        .library(name: "Problem72FilingDeadlineSequencer", targets: ["Problem72FilingDeadlineSequencer"])
    ],
    targets: [
        .target(name: "Problem03PermissionManager"),
        .testTarget(name: "Problem03PermissionManagerTests", dependencies: ["Problem03PermissionManager"]),
        .target(name: "Problem18InventoryReservationLedger"),
        .testTarget(name: "Problem18InventoryReservationLedgerTests", dependencies: ["Problem18InventoryReservationLedger"]),
        .target(name: "Problem10DispatchManager"),
        .testTarget(name: "Problem10DispatchManagerTests", dependencies: ["Problem10DispatchManager"]),
        .target(name: "Problem05MedicationTitration"),
        .testTarget(name: "Problem05MedicationTitrationTests", dependencies: ["Problem05MedicationTitration"]),
        .target(name: "Problem13ContractLifecycle"),
        .testTarget(name: "Problem13ContractLifecycleTests", dependencies: ["Problem13ContractLifecycle"]),
        .target(name: "Problem15TicTacToeEngine"),
        .testTarget(name: "Problem15TicTacToeEngineTests", dependencies: ["Problem15TicTacToeEngine"]),
        .target(name: "Problem02APIRateLimiter"),
        .testTarget(name: "Problem02APIRateLimiterTests", dependencies: ["Problem02APIRateLimiter"]),
        .target(name: "Problem11CoverageTracker"),
        .testTarget(name: "Problem11CoverageTrackerTests", dependencies: ["Problem11CoverageTracker"]),
        .target(name: "Problem19OfflineTelemetryBatchProcessor"),
        .testTarget(name: "Problem19OfflineTelemetryBatchProcessorTests", dependencies: ["Problem19OfflineTelemetryBatchProcessor"]),
        .target(name: "Problem21VersionedPayloadMigration"),
        .testTarget(name: "Problem21VersionedPayloadMigrationTests", dependencies: ["Problem21VersionedPayloadMigration"]),
        .target(name: "Problem22UndoRedoCommandStack"),
        .testTarget(name: "Problem22UndoRedoCommandStackTests", dependencies: ["Problem22UndoRedoCommandStack"]),
        .target(name: "Problem20OfflineSyncConflictResolver"),
        .testTarget(name: "Problem20OfflineSyncConflictResolverTests", dependencies: ["Problem20OfflineSyncConflictResolver"]),
        .target(name: "Problem23AvailabilityZoneMaintenancePlanner"),
        .testTarget(name: "Problem23AvailabilityZoneMaintenancePlannerTests", dependencies: ["Problem23AvailabilityZoneMaintenancePlanner"]),
        .target(name: "Problem24SensorDriftWindowDetector"),
        .testTarget(name: "Problem24SensorDriftWindowDetectorTests", dependencies: ["Problem24SensorDriftWindowDetector"]),
        .target(name: "Problem25WarehouseGridRoutePlanner"),
        .testTarget(name: "Problem25WarehouseGridRoutePlannerTests", dependencies: ["Problem25WarehouseGridRoutePlanner"]),
        .target(name: "Problem26FirmwareBundleBudgetPlanner"),
        .testTarget(name: "Problem26FirmwareBundleBudgetPlannerTests", dependencies: ["Problem26FirmwareBundleBudgetPlanner"]),
        .target(name: "Problem27LogTokenSegmenter"),
        .testTarget(name: "Problem27LogTokenSegmenterTests", dependencies: ["Problem27LogTokenSegmenter"]),
        .target(name: "Problem28BuildRegressionChainAnalyzer"),
        .testTarget(name: "Problem28BuildRegressionChainAnalyzerTests", dependencies: ["Problem28BuildRegressionChainAnalyzer"]),
        .target(name: "Problem29RuleGroupingAnalyzer"),
        .testTarget(name: "Problem29RuleGroupingAnalyzerTests", dependencies: ["Problem29RuleGroupingAnalyzer"]),
        .target(name: "Problem30DocumentRevisionDiffEngine"),
        .testTarget(name: "Problem30DocumentRevisionDiffEngineTests", dependencies: ["Problem30DocumentRevisionDiffEngine"]),
        .target(name: "Problem31PipelineBufferRemovalPlanner"),
        .testTarget(name: "Problem31PipelineBufferRemovalPlannerTests", dependencies: ["Problem31PipelineBufferRemovalPlanner"]),
        .target(name: "Problem32StorageArbitrageScheduler"),
        .testTarget(name: "Problem32StorageArbitrageSchedulerTests", dependencies: ["Problem32StorageArbitrageScheduler"]),
        .target(name: "Problem33FirmwareTelemetryBufferCompactor"),
        .testTarget(name: "Problem33FirmwareTelemetryBufferCompactorTests", dependencies: ["Problem33FirmwareTelemetryBufferCompactor"]),
        .target(name: "Problem34FloodplainPondingAnalyzer"),
        .testTarget(name: "Problem34FloodplainPondingAnalyzerTests", dependencies: ["Problem34FloodplainPondingAnalyzer"]),
        .target(name: "Problem35RedirectChainResolver"),
        .testTarget(name: "Problem35RedirectChainResolverTests", dependencies: ["Problem35RedirectChainResolver"]),
        .target(name: "Problem36DispatchWindowMatcher"),
        .testTarget(name: "Problem36DispatchWindowMatcherTests", dependencies: ["Problem36DispatchWindowMatcher"]),
        .target(name: "Problem37LedgerNettingFinder"),
        .testTarget(name: "Problem37LedgerNettingFinderTests", dependencies: ["Problem37LedgerNettingFinder"]),
        .target(name: "Problem68ClinicRoomBookingSelector"),
        .testTarget(name: "Problem68ClinicRoomBookingSelectorTests", dependencies: ["Problem68ClinicRoomBookingSelector"]),
        .target(name: "Problem70DepotChargerCapacitySizer"),
        .testTarget(name: "Problem70DepotChargerCapacitySizerTests", dependencies: ["Problem70DepotChargerCapacitySizer"]),
        .target(name: "Problem72FilingDeadlineSequencer"),
        .testTarget(name: "Problem72FilingDeadlineSequencerTests", dependencies: ["Problem72FilingDeadlineSequencer"])
    ]
)
