import Foundation

public enum PayloadError: Error, Equatable, Sendable { case malformedEnvelope; case malformedBody(version: Int); case missingRequiredField(field: String, version: Int); case unknownVersion(Int); case notImplemented }
public struct PayloadDocument: Equatable, Sendable { public let version: Int; public let fields: [String: String]; public init(version: Int, fields: [String: String]) { self.version = version; self.fields = fields } }
public struct DecodedPayload: Equatable, Sendable { public let version: Int; public let firstName: String; public let lastName: String; public let locale: String; public init(version: Int, firstName: String, lastName: String, locale: String) { self.version = version; self.firstName = firstName; self.lastName = lastName; self.locale = locale } }
public struct PayloadDecoder: Sendable { public let currentVersion: Int; public init(currentVersion: Int = 3) { self.currentVersion = currentVersion }; public func detectVersion(_ data: Data) -> Result<Int, PayloadError> { .failure(.notImplemented) }; public func payloadDocument(_ data: Data) -> Result<PayloadDocument, PayloadError> { .failure(.notImplemented) }; public func decodeCurrent(_ data: Data) -> Result<DecodedPayload, PayloadError> { .failure(.notImplemented) } }
public enum MigrationError: Error, Equatable, Sendable { case payload(PayloadError); case invalidStep(from: Int, to: Int); case missingStep(from: Int, to: Int); case stepFailed(from: Int, to: Int, reason: String); case notImplemented }
public protocol Migration: Sendable { var fromVersion: Int { get }; var toVersion: Int { get }; func apply(to document: PayloadDocument) -> Result<PayloadDocument, MigrationError> }
public enum MigrationOutcome: Equatable, Sendable { case migrated(fromVersion: Int, payload: DecodedPayload); case alreadyCurrent(DecodedPayload); case failed(MigrationError) }
public struct MigrationRegistry: Sendable { public let decoder: PayloadDecoder; public init(decoder: PayloadDecoder = PayloadDecoder(), migrations: [any Migration] = []) { self.decoder = decoder }; public mutating func register(_ migration: any Migration) {}; public func migrationChain(from data: Data) -> Result<[any Migration], MigrationError> { .failure(.notImplemented) }; public func migrate(_ data: Data) -> MigrationOutcome { .failed(.notImplemented) }; public func registeredVersions() -> [Int] { [] } }
public struct BatchPayload: Equatable, Sendable { public let id: String; public let data: Data; public init(id: String, data: Data) { self.id = id; self.data = data } }
public struct BatchPayloadResult: Equatable, Sendable { public let id: String; public let outcome: MigrationOutcome; public init(id: String, outcome: MigrationOutcome) { self.id = id; self.outcome = outcome } }
public struct MigrationReport: Equatable, Sendable { public let results: [BatchPayloadResult]; public let migratedCount: Int; public let alreadyCurrentCount: Int; public let failedCount: Int; public init(results: [BatchPayloadResult], migratedCount: Int, alreadyCurrentCount: Int, failedCount: Int) { self.results = results; self.migratedCount = migratedCount; self.alreadyCurrentCount = alreadyCurrentCount; self.failedCount = failedCount } }
public extension MigrationRegistry { func migrateBatch(_ payloads: [BatchPayload]) -> MigrationReport { MigrationReport(results: [], migratedCount: 0, alreadyCurrentCount: 0, failedCount: 0) } }
